// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnMojJ_tt1rjXMtNrx15W3apbZKktWmRM',
    appId: '1:500192069011:android:a531cb6029ade634289466',
    messagingSenderId: '500192069011',
    projectId: 'food-order-a2d6c',
    storageBucket: 'food-order-a2d6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcQDC1k0xvKZyhNHthxgWXOdiip8CaA-o',
    appId: '1:500192069011:ios:b43b8487181cc367289466',
    messagingSenderId: '500192069011',
    projectId: 'food-order-a2d6c',
    storageBucket: 'food-order-a2d6c.appspot.com',
    iosBundleId: 'com.example.order',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHNA42XcluTsb2GPpcxuEphDIIT639VJ0',
    appId: '1:500192069011:web:a27989be6b19457e289466',
    messagingSenderId: '500192069011',
    projectId: 'food-order-a2d6c',
    authDomain: 'food-order-a2d6c.firebaseapp.com',
    storageBucket: 'food-order-a2d6c.appspot.com',
    measurementId: 'G-Z1NVF45H20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcQDC1k0xvKZyhNHthxgWXOdiip8CaA-o',
    appId: '1:500192069011:ios:b43b8487181cc367289466',
    messagingSenderId: '500192069011',
    projectId: 'food-order-a2d6c',
    storageBucket: 'food-order-a2d6c.appspot.com',
    iosBundleId: 'com.example.order',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHNA42XcluTsb2GPpcxuEphDIIT639VJ0',
    appId: '1:500192069011:web:be5d9f7ab5b59a3f289466',
    messagingSenderId: '500192069011',
    projectId: 'food-order-a2d6c',
    authDomain: 'food-order-a2d6c.firebaseapp.com',
    storageBucket: 'food-order-a2d6c.appspot.com',
    measurementId: 'G-7W3NSM3S61',
  );

}